# Generated by Django 5.2.12 on 2026-03-14 07:32

from django.db import migrations, models


def copy_dimension_to_text_fields(apps, schema_editor):
    DimensionScore = apps.get_model('evaluations', 'DimensionScore')

    for item in DimensionScore.objects.select_related('dimension').all().iterator():
        if item.dimension_id:
            item.dimension_code = item.dimension.code
            item.dimension_name = item.dimension.name
            item.save(update_fields=['dimension_code', 'dimension_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionscore',
            name='dimension_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='维度代码'),
        ),
        migrations.AddField(
            model_name='dimensionscore',
            name='dimension_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='维度名称'),
        ),
        migrations.RunPython(copy_dimension_to_text_fields, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='dimensionscore',
            unique_together={('evaluation', 'dimension_code')},
        ),
        migrations.RemoveField(
            model_name='dimensionscore',
            name='dimension',
        ),
    ]
