# Generated by Django 5.2.12 on 2026-03-14 07:49

import django.db.models.deletion
from django.db import migrations, models


def migrate_voiceanalysis_message_to_round(apps, schema_editor):
    VoiceAnalysis = apps.get_model('evaluations', 'VoiceAnalysis')

    for item in VoiceAnalysis.objects.select_related('message').all().iterator():
        if item.message_id:
            item.round_id = item.message.round_id
            item.save(update_fields=['round'])


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_dimensionscore_unique_together_and_more'),
        ('interviews', '0003_interviewround_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceanalysis',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_analyses', to='interviews.interviewround', verbose_name='轮次'),
        ),
        migrations.RunPython(migrate_voiceanalysis_message_to_round, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='voiceanalysis',
            name='message',
        ),
        migrations.DeleteModel(
            name='DimensionScore',
        ),
    ]
