# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(verbose_name='综合得分')),
                ('overall_comment', models.TextField(verbose_name='综合评价')),
                ('technical_score', models.FloatField(verbose_name='技术得分')),
                ('communication_score', models.FloatField(verbose_name='沟通得分')),
                ('logic_score', models.FloatField(verbose_name='逻辑得分')),
                ('adaptability_score', models.FloatField(verbose_name='应变得分')),
                ('highlights', models.JSONField(default=list, verbose_name='亮点')),
                ('weaknesses', models.JSONField(default=list, verbose_name='不足')),
                ('suggestions', models.JSONField(default=list, verbose_name='建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评估记录',
                'verbose_name_plural': '评估记录',
                'db_table': 'evaluations',
            },
        ),
        migrations.CreateModel(
            name='VoiceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.FloatField(verbose_name='时长(秒)')),
                ('speech_rate', models.FloatField(verbose_name='语速(字/分钟)')),
                ('clarity_score', models.FloatField(verbose_name='清晰度得分')),
                ('confidence_score', models.FloatField(verbose_name='自信度得分')),
                ('emotion', models.CharField(blank=True, max_length=50, verbose_name='情感')),
                ('transcript', models.TextField(blank=True, verbose_name='转录文本')),
                ('analysis_details', models.JSONField(default=dict, verbose_name='分析详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '语音分析',
                'verbose_name_plural': '语音分析',
                'db_table': 'voice_analyses',
            },
        ),
        migrations.CreateModel(
            name='DimensionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='得分')),
                ('max_score', models.FloatField(default=100, verbose_name='满分')),
                ('comment', models.TextField(blank=True, verbose_name='评语')),
                ('evidence', models.JSONField(default=list, verbose_name='证据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.positiondimension', verbose_name='维度')),
            ],
            options={
                'verbose_name': '维度评分',
                'verbose_name_plural': '维度评分',
                'db_table': 'dimension_scores',
            },
        ),
    ]
