# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='interviews.interview', verbose_name='面试'),
        ),
        migrations.AddField(
            model_name='dimensionscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_scores', to='evaluations.evaluation', verbose_name='评估'),
        ),
        migrations.AddField(
            model_name='voiceanalysis',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_analysis', to='interviews.interviewmessage', verbose_name='消息'),
        ),
        migrations.AlterUniqueTogether(
            name='dimensionscore',
            unique_together={('evaluation', 'dimension')},
        ),
    ]
