# Generated by Django 5.2.12 on 2026-03-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_remove_voiceanalysis_message_voiceanalysis_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_code', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], max_length=16, unique=True, verbose_name='难度编码')),
                ('difficulty_name', models.CharField(max_length=32, verbose_name='难度名称')),
                ('answer_time_seconds', models.IntegerField(verbose_name='单轮默认答题时长(秒)')),
                ('technical_chain_count', models.IntegerField(verbose_name='技术知识链数量')),
                ('project_chain_count', models.IntegerField(verbose_name='项目深挖链数量')),
                ('scenario_chain_count', models.IntegerField(verbose_name='场景题链数量')),
                ('technical_max_followup_depth', models.IntegerField(verbose_name='技术链最大追问深度')),
                ('project_max_followup_depth', models.IntegerField(verbose_name='项目链最大追问深度')),
                ('scenario_max_followup_depth', models.IntegerField(verbose_name='场景链最大追问深度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '难度配置',
                'verbose_name_plural': '难度配置',
                'db_table': 'difficulty_config',
            },
        ),
    ]
