# Generated by Django 5.2.12 on 2026-03-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_difficultyconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultyconfig',
            name='difficulty_code',
            field=models.CharField(max_length=16, unique=True, verbose_name='难度编码'),
        ),
    ]
