# Generated by Django 5.2.12 on 2026-03-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_alter_difficultyconfig_difficulty_code'),
        ('interviews', '0010_interviewroundaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceanalysis',
            name='audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_analysis', to='interviews.interviewroundaudio', verbose_name='音频'),
        ),
    ]
