# Generated by Django 5.2.12 on 2026-03-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0015_remove_imentiv_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voiceanalysis",
            name="audio_clarity_score",
            field=models.FloatField(verbose_name="音频清晰度得分"),
        ),
    ]
