# Generated by Django 5.2.12 on 2026-03-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0017_restore_imentiv_status_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voiceanalysis",
            name="asr_confidence",
        ),
        migrations.RemoveField(
            model_name="voiceanalysis",
            name="overall_clarity",
        ),
    ]
