# Generated by Django 5.2.12 on 2026-03-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0018_remove_voiceanalysis_asr_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceanalysis",
            name="speech_rate_level",
            field=models.CharField(
                choices=[("slow", "慢"), ("normal", "正常"), ("fast", "快")],
                default="normal",
                help_text="根据speech_rate自动划分：慢(<180)，正常(180-260)，快(>260)",
                max_length=8,
                verbose_name="语速评价（慢/正常/快）",
            ),
        ),
    ]
