# Generated by Django 5.2.12 on 2026-03-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0019_voiceanalysis_speech_rate_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceanalysis",
            name="silence_ratio_level",
            field=models.CharField(
                choices=[
                    ("fluent", "流利"),
                    ("good", "良好"),
                    ("medium", "中等偏下"),
                    ("poor", "较差"),
                ],
                default="good",
                help_text="依据silence_ratio自动划分：流利(<=0.15)，良好(<=0.25)，中等偏下(<=0.35)，较差(>0.35)",
                max_length=12,
                verbose_name="静音比例评价",
            ),
        ),
    ]
