# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('java_backend', 'Java后端工程师'), ('web_frontend', 'Web前端工程师'), ('test_engineer', '测试工程师')], max_length=50, unique=True, verbose_name='岗位代码')),
                ('name', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('description', models.TextField(blank=True, verbose_name='岗位描述')),
                ('tech_stack', models.JSONField(default=list, verbose_name='技术栈')),
                ('required_skills', models.JSONField(default=list, verbose_name='必备技能')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'db_table': 'job_positions',
            },
        ),
        migrations.CreateModel(
            name='PositionDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('technical', '技术能力'), ('communication', '沟通表达'), ('logic', '逻辑思维'), ('adaptability', '应变能力'), ('project_experience', '项目经验')], max_length=50, verbose_name='维度代码')),
                ('name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('description', models.TextField(blank=True, verbose_name='维度描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='positions.jobposition', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '岗位评估维度',
                'verbose_name_plural': '岗位评估维度',
                'db_table': 'position_dimensions',
                'unique_together': {('position', 'code')},
            },
        ),
    ]
