# Generated by Django 5.2.12 on 2026-03-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_dimensionscore_unique_together_and_more'),
        ('positions', '0001_initial'),
        ('recommendations', '0003_alter_recommendation_related_dimension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PositionDimension',
        ),
    ]
