# Generated by Django 5.2.12 on 2026-03-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_delete_positiondimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='岗位代码'),
        ),
    ]
