# Generated by Django 5.2.12 on 2026-04-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_alter_jobposition_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobKnowledge',
            fields=[
                ('id_job_knowledge', models.AutoField(db_column='id_job_knowledge', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='知识点名称')),
                ('serial_number', models.IntegerField(verbose_name='序号')),
                ('job_id', models.IntegerField(db_column='job_id', verbose_name='岗位ID')),
            ],
            options={
                'verbose_name': '岗位知识点',
                'verbose_name_plural': '岗位知识点',
                'db_table': 'job_knowledge',
                'managed': False,
            },
        ),
    ]
