# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        ('positions', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_interviews', models.IntegerField(default=0, verbose_name='总面试次数')),
                ('total_questions_answered', models.IntegerField(default=0, verbose_name='总答题数')),
                ('avg_overall_score', models.FloatField(default=0, verbose_name='平均综合得分')),
                ('avg_technical_score', models.FloatField(default=0, verbose_name='平均技术得分')),
                ('avg_communication_score', models.FloatField(default=0, verbose_name='平均沟通得分')),
                ('avg_logic_score', models.FloatField(default=0, verbose_name='平均逻辑得分')),
                ('completed_recommendations', models.IntegerField(default=0, verbose_name='已完成推荐数')),
                ('skill_gaps', models.JSONField(default=list, verbose_name='技能缺口')),
                ('improvement_areas', models.JSONField(default=list, verbose_name='改进领域')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户进度',
                'verbose_name_plural': '用户进度',
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('knowledge', '知识点补充'), ('question', '题目推荐'), ('resource', '学习资源'), ('practice', '练习建议')], max_length=20, verbose_name='推荐类型')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='interviews.interview', verbose_name='面试')),
                ('related_dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.positiondimension', verbose_name='关联维度')),
                ('related_knowledge_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.knowledgepoint', verbose_name='关联知识点')),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
                'db_table': 'recommendations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
