# Generated by Django 5.2.12 on 2026-03-14 07:32

from django.db import migrations, models


def copy_related_dimension_to_text(apps, schema_editor):
    Recommendation = apps.get_model('recommendations', 'Recommendation')

    for item in Recommendation.objects.select_related('related_dimension').all().iterator():
        if item.related_dimension_id:
            item.related_dimension_text = item.related_dimension.name
            item.save(update_fields=['related_dimension_text'])


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='related_dimension_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关联维度'),
        ),
        migrations.RunPython(copy_related_dimension_to_text, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='recommendation',
            name='related_dimension',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='related_dimension_text',
            new_name='related_dimension',
        ),
    ]
