# Generated by Django 5.2.12 on 2026-06-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0003_alter_recommendation_related_dimension"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobKnowledge",
            fields=[
                (
                    "id_job_knowledge",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=45)),
                ("serial_number", models.IntegerField()),
                ("job_id", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "岗位知识点",
                "verbose_name_plural": "岗位知识点",
                "db_table": "job_knowledge",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserKnowledgeMatrics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("logic", models.IntegerField()),
                ("accuracy", models.IntegerField()),
            ],
            options={
                "verbose_name": "用户知识点掌握记录",
                "verbose_name_plural": "用户知识点掌握记录",
                "db_table": "user_knowledge_matrics",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VoiceLlmResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "overall_audio_score",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "speech_rate_and_rhythm_score",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                ("speech_rate_and_rhythm", models.TextField()),
                ("fluency_score", models.DecimalField(decimal_places=1, max_digits=5)),
                ("fluency", models.TextField()),
                (
                    "confidence_and_voice_energy_score",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                ("confidence_and_voice_energy", models.TextField()),
                (
                    "emotional_stability_and_tone_score",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                ("emotional_stability_and_tone", models.TextField()),
                ("strengths", models.TextField()),
                ("improvements", models.TextField()),
                ("position_communication_tips", models.TextField()),
                ("encouragement", models.TextField()),
                ("llm_model", models.CharField(max_length=120)),
                ("prompt_version", models.CharField(max_length=40)),
                ("raw_input_json", models.JSONField(default=dict)),
                ("raw_output_json", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField()),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "语音LLM分析结果",
                "verbose_name_plural": "语音LLM分析结果",
                "db_table": "voice_llm_results",
                "managed": False,
            },
        ),
    ]
