# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('positions', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='learningpathitem',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.learningpath', verbose_name='学习路径'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='knowledge_points',
            field=models.ManyToManyField(blank=True, related_name='resources', to='questions.knowledgepoint', verbose_name='关联知识点'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='positions.jobposition', verbose_name='岗位'),
        ),
        migrations.AddField(
            model_name='learningpathitem',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningresource', verbose_name='资源'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='resources',
            field=models.ManyToManyField(through='learning.LearningPathItem', to='learning.learningresource', verbose_name='资源'),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathitem',
            unique_together={('learning_path', 'resource')},
        ),
    ]
