# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='interviewmessage',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interviews.interview', verbose_name='面试'),
        ),
        migrations.AddField(
            model_name='interviewmessage',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.question', verbose_name='关联题目'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.questioncategory', verbose_name='题目分类'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='interviews.interview', verbose_name='面试'),
        ),
        migrations.AddField(
            model_name='interviewmessage',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interviews.interviewround', verbose_name='轮次'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewround',
            unique_together={('interview', 'round_number')},
        ),
    ]
