# Generated by Django 5.2.12 on 2026-03-14 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_rounds', to='questions.question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='question_content',
            field=models.TextField(blank=True, verbose_name='问题内容快照'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='user_answer',
            field=models.TextField(blank=True, verbose_name='用户回答'),
        ),
    ]
