# Generated by Django 5.2.12 on 2026-03-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_remove_voiceanalysis_message_voiceanalysis_round_and_more'),
        ('interviews', '0003_interviewround_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewMessage',
        ),
    ]
