# Generated by Django 5.2.12 on 2026-03-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_delete_interviewmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='total_rounds',
            field=models.IntegerField(default=0, verbose_name='总轮次'),
        ),
        migrations.CreateModel(
            name='InterviewRoundAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(verbose_name='综合得分')),
                ('overall_comment', models.TextField(verbose_name='综合评价')),
                ('technical_score', models.FloatField(verbose_name='技术得分')),
                ('communication_score', models.FloatField(verbose_name='沟通得分')),
                ('logic_score', models.FloatField(verbose_name='逻辑得分')),
                ('adaptability_score', models.FloatField(verbose_name='应变得分')),
                ('highlights', models.JSONField(default=list, verbose_name='亮点')),
                ('weaknesses', models.JSONField(default=list, verbose_name='不足')),
                ('suggestions', models.JSONField(default=list, verbose_name='建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='interviews.interviewround', verbose_name='面试轮次')),
            ],
            options={
                'verbose_name': '轮次分析结果',
                'verbose_name_plural': '轮次分析结果',
                'db_table': 'interview_round_analyses',
            },
        ),
    ]
