# Generated by Django 5.2.12 on 2026-03-22 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_difficultyconfig'),
        ('interviews', '0005_interview_total_rounds_interviewroundanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='answered_questions',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='interview',
            name='difficulty_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='evaluations.difficultyconfig', verbose_name='难度配置'),
        ),
        migrations.AddField(
            model_name='interview',
            name='enable_project_questions',
            field=models.BooleanField(default=True, verbose_name='是否选择项目经历题'),
        ),
        migrations.AddField(
            model_name='interview',
            name='enable_scenario_questions',
            field=models.BooleanField(default=True, verbose_name='是否选择场景题'),
        ),
        migrations.AddField(
            model_name='interview',
            name='enable_technical_questions',
            field=models.BooleanField(default=True, verbose_name='是否选择技术知识题'),
        ),
    ]
