# Generated by Django 5.2.12 on 2026-03-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_remove_interview_answered_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='面试名称'),
        ),
    ]
