# Generated by Django 5.2.12 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_interview_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='chain_index',
            field=models.IntegerField(default=1, verbose_name='提问链编号'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='followup_depth',
            field=models.IntegerField(default=0, verbose_name='追问深度'),
        ),
    ]
