# Generated by Django 5.2.12 on 2026-03-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_interviewround_chain_index_and_followup_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='actual_duration',
            field=models.IntegerField(default=0, verbose_name='实际面试时长(秒)'),
        ),
        migrations.AddField(
            model_name='interview',
            name='pause_count',
            field=models.IntegerField(default=0, verbose_name='暂停次数'),
        ),
        migrations.AddField(
            model_name='interview',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='暂停时间'),
        ),
        migrations.AddField(
            model_name='interview',
            name='total_pause_duration',
            field=models.IntegerField(default=0, verbose_name='总暂停时长(秒)'),
        ),
    ]
