# Generated by Django 5.2.12 on 2026-03-24 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_interview_actual_duration_interview_pause_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRoundAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500, verbose_name='音频URL')),
                ('file_key', models.CharField(max_length=255, unique=True, verbose_name='存储Key')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('codec', models.CharField(blank=True, max_length=50, verbose_name='编码')),
                ('sample_rate', models.IntegerField(blank=True, null=True, verbose_name='采样率')),
                ('channels', models.IntegerField(blank=True, null=True, verbose_name='声道数')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='时长(秒)')),
                ('upload_status', models.CharField(choices=[('uploaded', '已上传'), ('failed', '上传失败'), ('deleted', '已删除')], default='uploaded', max_length=20, verbose_name='上传状态')),
                ('asr_status', models.CharField(choices=[('pending', '待处理'), ('running', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='转写状态')),
                ('analysis_status', models.CharField(choices=[('pending', '待处理'), ('running', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='分析状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='interviews.interviewround', verbose_name='轮次')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '轮次音频',
                'verbose_name_plural': '轮次音频',
                'db_table': 'interview_round_audios',
                'indexes': [models.Index(fields=['created_at'], name='interview_r_created_de95a4_idx'), models.Index(fields=['asr_status'], name='interview_r_asr_sta_5c698a_idx'), models.Index(fields=['analysis_status'], name='interview_r_analysi_3fe644_idx')],
            },
        ),
    ]
