# Generated by Django 5.2.12 on 2026-03-27 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0010_interviewroundaudio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewroundaudio",
            name="imentiv_analysis_status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("running", "处理中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="iMentiv分析状态",
            ),
        ),
        migrations.AddField(
            model_name="interviewroundaudio",
            name="imentiv_error_message",
            field=models.TextField(blank=True, verbose_name="iMentiv错误信息"),
        ),
        migrations.AddIndex(
            model_name="interviewroundaudio",
            index=models.Index(
                fields=["imentiv_analysis_status"],
                name="interview_r_imentiv_810115_idx",
            ),
        ),
    ]
