# Generated by Django 5.2.12 on 2026-04-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0014_interviewroundanalysis_job_matching_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='user_project_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='关联用户项目ID'),
        ),
    ]
