# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('content', models.TextField(verbose_name='报告内容')),
                ('pdf_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='PDF文件URL')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('key_findings', models.JSONField(default=list, verbose_name='关键发现')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='evaluations.evaluation', verbose_name='评估')),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interviews.interview', verbose_name='面试')),
            ],
            options={
                'verbose_name': '评估报告',
                'verbose_name_plural': '评估报告',
                'db_table': 'reports',
            },
        ),
    ]
