# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('technical', '技术知识'), ('project', '项目经历'), ('scenario', '场景题'), ('behavioral', '行为题')], max_length=50, unique=True, verbose_name='分类代码')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目分类',
                'verbose_name_plural': '题目分类',
                'db_table': 'question_categories',
            },
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='知识点名称')),
                ('description', models.TextField(blank=True, verbose_name='知识点描述')),
                ('difficulty', models.IntegerField(default=1, verbose_name='难度等级')),
                ('vector_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='向量ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_points', to='positions.jobposition', verbose_name='所属岗位')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'db_table': 'knowledge_points',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('reference_answer', models.TextField(blank=True, verbose_name='参考答案')),
                ('difficulty', models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], default=1, verbose_name='难度')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('follow_up_questions', models.JSONField(blank=True, default=list, verbose_name='追问模板')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('knowledge_points', models.ManyToManyField(blank=True, related_name='questions', to='questions.knowledgepoint', verbose_name='关联知识点')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='positions.jobposition', verbose_name='岗位')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questioncategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '面试题',
                'verbose_name_plural': '面试题',
                'db_table': 'questions',
            },
        ),
    ]
