# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习路径项',
                'verbose_name_plural': '学习路径项',
                'db_table': 'learning_path_items',
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='资源标题')),
                ('resource_type', models.CharField(choices=[('article', '文章'), ('video', '视频'), ('book', '书籍'), ('course', '课程'), ('practice', '练习题')], max_length=20, verbose_name='资源类型')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('difficulty', models.IntegerField(default=1, verbose_name='难度')),
                ('estimated_time', models.IntegerField(blank=True, null=True, verbose_name='预计学习时长(分钟)')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学习资源',
                'verbose_name_plural': '学习资源',
                'db_table': 'learning_resources',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='路径标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('progress', models.FloatField(default=0, verbose_name='进度')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='positions.jobposition', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '学习路径',
                'verbose_name_plural': '学习路径',
                'db_table': 'learning_paths',
            },
        ),
    ]
