# Generated by Django 5.2.12 on 2026-03-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('interviewer', '面试官'), ('candidate', '候选人'), ('system', '系统')], max_length=20, verbose_name='角色')),
                ('message_type', models.CharField(choices=[('question', '问题'), ('answer', '回答'), ('follow_up', '追问'), ('feedback', '反馈'), ('system', '系统消息')], max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('audio_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='语音文件URL')),
                ('sequence', models.IntegerField(verbose_name='序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '面试消息',
                'verbose_name_plural': '面试消息',
                'db_table': 'interview_messages',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='轮次')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '面试轮次',
                'verbose_name_plural': '面试轮次',
                'db_table': 'interview_rounds',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('mode', models.CharField(choices=[('text', '文本模式'), ('voice', '语音模式'), ('mixed', '混合模式')], default='text', max_length=20, verbose_name='交互模式')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('total_questions', models.IntegerField(default=0, verbose_name='总题数')),
                ('answered_questions', models.IntegerField(default=0, verbose_name='已答题数')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='positions.jobposition', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '面试记录',
                'verbose_name_plural': '面试记录',
                'db_table': 'interviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
