"""
Django settings for AI_Interview project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 本地密钥：项目根目录或 backend 目录下的 .env（勿提交仓库，已在 .gitignore）
try:
    from dotenv import load_dotenv

    _repo_root = BASE_DIR.parent
    load_dotenv(_repo_root / ".env")
    load_dotenv(BASE_DIR / ".env", override=True)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=*0cf_-*9zv1ogzn^l=@je7xc=aznyb(#^#41%*-xo$3ow-+4v"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "drf_yasg",
    "users",
    "positions",
    "questions",
    "interviews",
    "evaluations",
    "reports",
    "recommendations",
    "pathway",
    "learning",
    "user_projects",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AI_Interview.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AI_Interview.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ai_interview_database",
        "USER": "user",
        "PASSWORD": "password123",
        "HOST": "121.40.66.75",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# 单文件上传大小限制（默认20MB）
AUDIO_UPLOAD_MAX_BYTES = 20 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

# JWT配置
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# REST Framework配置
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# CORS配置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "access-control-allow-origin",
    "access-control-allow-headers",
    "access-control-allow-methods",
]

# LLM 配置（OpenAI 兼容接口）
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "https://api.siliconflow.cn/v1")
LLM_API_KEY = os.getenv(
    "LLM_API_KEY", "sk-dluftqepbembchzclitolntrxnmpfukijjivfjxkwyabtfnk"
)
LLM_MODEL = os.getenv("LLM_MODEL", "deepseek-ai/DeepSeek-V3.2")
LLM_TIMEOUT_SECONDS = int(os.getenv("LLM_TIMEOUT_SECONDS", "90"))
LLM_RETRY_COUNT = int(os.getenv("LLM_RETRY_COUNT", "2"))
LLM_RETRY_BACKOFF_SECONDS = float(os.getenv("LLM_RETRY_BACKOFF_SECONDS", "1.5"))

# 阿里云百炼 Model Studio 应用（Application.call），用于按岗位绑定不同 app_id 与追问 session
# 文档示例：api_key + app_id + prompt；追问时传入上一轮 response.output.session_id
DASHSCOPE_API_KEY = os.getenv("DASHSCOPE_API_KEY", "")
# 可选：按岗位 code 映射多个应用，例如 {"java_backend":"uuid","llm":"uuid"}
DASHSCOPE_APP_IDS_JSON = os.getenv("DASHSCOPE_APP_IDS_JSON", "{}")
# 也可单独配置常用岗位（与 JSON 二选一或混用，JSON 优先）
DASHSCOPE_APP_ID_JAVA_BACKEND = os.getenv("DASHSCOPE_APP_ID_JAVA_BACKEND", "")
DASHSCOPE_APP_ID_LLM = os.getenv("DASHSCOPE_APP_ID_LLM", "")
DASHSCOPE_APP_ID_DEFAULT = os.getenv("DASHSCOPE_APP_ID_DEFAULT", "")

# 面试出题：True 时跳过题库，直接按题型 + difficulty_config + job_knowledge 走生成 prompt（推荐与百炼/LLM 联用）
INTERVIEW_PREFER_LLM_OVER_BANK = os.getenv(
    "INTERVIEW_PREFER_LLM_OVER_BANK", "true"
).lower() in ("1", "true", "yes", "on")

# iMentiv 音频情感分析配置（硬编码，仅用于本地调试）
IMENTIV_BASE_URL = "https://api.imentiv.ai"
IMENTIV_API_KEY = "wzSHXmW6vUZiuHsAz6c87eiFhsnnW7iX9lUk2z4dvUYs5zIUyeMItBhGHlz_o5Wrg6s"
IMENTIV_LANGUAGE = "zh"
IMENTIV_TIMEOUT_SECONDS = 60
IMENTIV_POLL_INTERVAL_SECONDS = 2.0
IMENTIV_MAX_POLLS = 30
IMENTIV_REFERER = "http://127.0.0.1:8000/"
IMENTIV_IS_INTERNAL = True

# Celery 配置
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = TIME_ZONE

# 本地 ASR 配置
ASR_LANGUAGE = os.getenv("ASR_LANGUAGE", "zh")
ASR_MODEL_SIZE = os.getenv("ASR_MODEL_SIZE", "small")
ASR_BEAM_SIZE = int(os.getenv("ASR_BEAM_SIZE", "5"))
ASR_DEVICE = os.getenv("ASR_DEVICE", "cpu")
ASR_COMPUTE_TYPE = os.getenv("ASR_COMPUTE_TYPE", "int8")
ASR_FORCE_SIMPLIFIED = os.getenv("ASR_FORCE_SIMPLIFIED", "true").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
ASR_PREPROCESS_ENABLED = os.getenv("ASR_PREPROCESS_ENABLED", "true").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
ASR_TARGET_SR = int(os.getenv("ASR_TARGET_SR", "16000"))
ASR_TRIM_TOP_DB = float(os.getenv("ASR_TRIM_TOP_DB", "30"))
ASR_NOISE_REDUCE_STRENGTH = float(os.getenv("ASR_NOISE_REDUCE_STRENGTH", "1.4"))
ASR_TARGET_RMS = float(os.getenv("ASR_TARGET_RMS", "0.08"))
