# Generated by Django 5.2.12 on 2026-04-08 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='技术总分')),
                ('expression_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='表达总分')),
                ('dimensions_json', models.JSONField(default=dict, verbose_name='维度分数')),
                ('weaknesses_json', models.JSONField(default=list, verbose_name='短板列表')),
                ('strengths_json', models.JSONField(default=list, verbose_name='优势列表')),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='结论置信度')),
                ('snapshot_time', models.DateTimeField(verbose_name='快照时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_profiles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '路径画像快照',
                'verbose_name_plural': '路径画像快照',
                'db_table': 'pathway_profiles',
                'ordering': ['-snapshot_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PathwayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('paused', '已暂停')], default='draft', max_length=20, verbose_name='计划状态')),
                ('cycle_days', models.IntegerField(default=7, verbose_name='周期天数')),
                ('goal_summary', models.TextField(verbose_name='目标总结')),
                ('expected_gain_json', models.JSONField(default=dict, verbose_name='预计提升')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_plans', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='pathway.pathwayprofile', verbose_name='画像快照')),
            ],
            options={
                'verbose_name': '路径计划',
                'verbose_name_plural': '路径计划',
                'db_table': 'pathway_plans',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PathwayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField(verbose_name='第几天')),
                ('task_type', models.CharField(choices=[('resource', '学习资源'), ('question', '题目练习'), ('practice', '表达训练'), ('review', '复盘任务')], max_length=20, verbose_name='任务类型')),
                ('source_type', models.CharField(max_length=30, verbose_name='来源类型')),
                ('source_id', models.BigIntegerField(blank=True, null=True, verbose_name='来源ID')),
                ('title', models.CharField(max_length=300, verbose_name='任务标题')),
                ('reason', models.TextField(verbose_name='推荐理由')),
                ('estimated_minutes', models.IntegerField(default=20, verbose_name='预计时长')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待完成'), ('done', '已完成'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='完成状态')),
                ('completion_note', models.TextField(blank=True, default='', verbose_name='完成备注')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pathway.pathwayplan', verbose_name='所属计划')),
            ],
            options={
                'verbose_name': '路径任务',
                'verbose_name_plural': '路径任务',
                'db_table': 'pathway_tasks',
                'ordering': ['day_index', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PathwayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('generated', '路径生成'), ('task_done', '任务完成'), ('reviewed', '复盘完成'), ('adjusted', '计划调整')], max_length=20, verbose_name='事件类型')),
                ('payload_json', models.JSONField(default=dict, verbose_name='事件详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_events', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pathway.pathwayplan', verbose_name='关联计划')),
            ],
            options={
                'verbose_name': '路径事件',
                'verbose_name_plural': '路径事件',
                'db_table': 'pathway_events',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='pathway_eve_user_id_e9bef4_idx'), models.Index(fields=['plan', 'event_type'], name='pathway_eve_plan_id_6b603f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pathwayprofile',
            index=models.Index(fields=['user', 'snapshot_time'], name='pathway_pro_user_id_1929cd_idx'),
        ),
        migrations.AddIndex(
            model_name='pathwayplan',
            index=models.Index(fields=['user', 'status'], name='pathway_pla_user_id_fc3482_idx'),
        ),
        migrations.AddIndex(
            model_name='pathwaytask',
            index=models.Index(fields=['plan', 'day_index'], name='pathway_tas_plan_id_5c684f_idx'),
        ),
        migrations.AddIndex(
            model_name='pathwaytask',
            index=models.Index(fields=['plan', 'status'], name='pathway_tas_plan_id_b86a0e_idx'),
        ),
    ]
