# Generated by Django 5.2.12 on 2026-04-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pathway", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PathwayGenerationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "排队中"), ("running", "生成中"), ("success", "成功"), ("failed", "失败")],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("cycle_days", models.IntegerField(default=7, verbose_name="周期天数")),
                ("current_day", models.IntegerField(default=0, verbose_name="当前生成到第几天")),
                ("total_days", models.IntegerField(default=7, verbose_name="总天数")),
                ("progress_percent", models.IntegerField(default=0, verbose_name="进度百分比")),
                ("message", models.CharField(blank=True, default="", max_length=255, verbose_name="状态文案")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("meta_json", models.JSONField(default=dict, verbose_name="元信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_jobs",
                        to="pathway.pathwayplan",
                        verbose_name="生成结果计划",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathway_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "路径生成任务",
                "verbose_name_plural": "路径生成任务",
                "db_table": "pathway_generation_jobs",
                "ordering": ["-id"],
            },
        ),
        migrations.AddIndex(
            model_name="pathwaygenerationjob",
            index=models.Index(fields=["user", "status"], name="pathway_gen_user_id_8b9f57_idx"),
        ),
        migrations.AddIndex(
            model_name="pathwaygenerationjob",
            index=models.Index(fields=["created_at"], name="pathway_gen_created_0d3d36_idx"),
        ),
    ]
