# Generated by Django 5.2.12 on 2026-06-30 13:32

from django.db import migrations


def rename_indexes_if_possible(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        renames = [
            (
                "pathway_external_resources",
                "pathway_ext_focus_i_0e657d_idx",
                "pathway_ext_focus_a_f55b9a_idx",
            ),
            (
                "pathway_generation_jobs",
                "pathway_gen_user_id_8b9f57_idx",
                "pathway_gen_user_id_e7cb40_idx",
            ),
            (
                "pathway_generation_jobs",
                "pathway_gen_created_0d3d36_idx",
                "pathway_gen_created_7d77a5_idx",
            ),
        ]

        for table_name, old_name, new_name in renames:
            cursor.execute(f"SHOW INDEX FROM `{table_name}`")
            existing_indexes = [row[2] for row in cursor.fetchall()]
            if old_name in existing_indexes:
                cursor.execute(
                    f"ALTER TABLE `{table_name}` RENAME INDEX `{old_name}` TO `{new_name}`"
                )


class Migration(migrations.Migration):

    dependencies = [
        ("pathway", "0004_enrich_external_resource_topics"),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_possible, migrations.RunPython.noop),
    ]
